---
- name: Configure EC2 Machine
  become: true
  hosts:  app
  
  tasks:
    - name: Install Utils
      yum:
        name: 
          - yum-utils
          - libxcrypt-compat
          - python3-pip
          - docker
          - git
        state: latest

    - name: Install docker-compose
      remote_user: ec2-user
      get_url:
        url : https://github.com/docker/compose/releases/download/1.23.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '+x'
    
    - name: install 'Docker SDK for Python'
      become: false
      pip:
        name:
          - docker
          - docker-compose

    - name: Add user to the docker group
      user:
        name: "ec2-user"
        groups: docker
        append: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
