---
- name: Prepare EC2 Machine
  become: true
  hosts: all
  
  tasks:
    - name: Install Utils
      yum:
        name: 
          - yum-utils
          - python3-pip
          - docker
          - git
        state: latest

    - name: Install requests python package
      ansible.builtin.pip:
        name:
          - requests
          - urllib3==1.26.6

    - name: Install docker-compose
      remote_user: ec2-user
      get_url:
        url : https://github.com/docker/compose/releases/download/1.23.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '+x'

    - name: install 'Docker SDK for Python'
      become: false
      pip:
        name:
          - docker
          - docker-compose

    - name: Add user to the docker group
      user:
        name: "ec2-user"
        groups: docker
        append: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Clone the Git repository
      git:
        repo: "https://github.com/bardahan/todo_app.git"
        version: "wip"
        dest: "/usr/app"

    - name: Build dockerfiles
      command: /usr/local/bin/docker-compose -f /usr/app/docker-compose.yml build --no-cache

    - name: Bring up the Docker Compose project
      command: /usr/local/bin/docker-compose -f /usr/app/docker-compose.yml up -d --force-recreate
      environment:
        DB_SCHEME: $DB_NAME
        DB_HOST: $DB_HOSTNAME
        DB_PASS: $DB_PASSWORD
        DB_USER: $DB_USERNAME
        API_BASE_URL: http://$API_BASE_URL:8001
