---
- name: Prepare EC2 Machine
  become: true
  hosts: all
  
  tasks:
    - name: Install Utils
      yum:
        name: 
          - yum-utils
          - python3-pip
          - docker
          - git
        state: latest

    - name: Install requests python package
      ansible.builtin.pip:
        name:
          - requests
          - urllib3==1.26.6

    - name: install 'Docker SDK for Python'
      become: false
      pip:
        name:
          - docker

    - name: Add user to the docker group
      user:
        name: "ec2-user"
        groups: docker
        append: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create nginx container
      docker_container:
        name: nginx
        restart_policy: always
        image: nginx:1.21.0
        ports:
          - "80:80"
